server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka

spring:
  application:
    name: notification
  profiles:
    active: ${PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost}:${POSTGRES_PORT:5423}/${POSTGRES_DATABASE:notification_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    show-sql: true

feign:
  circuitbreaker:
    enabled: true
